export default {
  path: '/demo',
  name: 'demo',
  parentPath: '/',
  redirect: '/demo/table',
  icon: '',
  menu: true,
  order: 100,
  children: [
    {
      path: 'table',
      name: 'table',
      parentPath: '/demo',
      icon: '',
      menu: true,
    },
    {
      path: 'table2',
      name: 'api-table',
      parentPath: '/demo',
      icon: '',
      menu: true,
    },
    {
      path: 'search',
      name: 'search',
      parentPath: '/demo',
      icon: '',
      menu: true,
    },
    {
      path: 'search2',
      name: 'api-search',
      parentPath: '/demo',
      icon: '',
      menu: true,
    },
    {
      path: 'form',
      name: 'form',
      parentPath: '/demo',
      icon: '',
      menu: true,
    },
  ],
}
