export default {
  path: '/system',
  name: 'system',
  parentPath: '/',
  redirect: '/system/log',
  icon: '',
  menu: true,
  order: 80,
  children: [
    {
      path: 'log',
      name: 'log',
      parentPath: '/system',
      icon: '',
      menu: true,
    },
    {
      path: 'params',
      name: 'params',
      parentPath: '/system',
      icon: '',
      menu: true,
    },
    {
      path: 'menu',
      name: 'menu',
      parentPath: '/system',
      icon: '',
      menu: true,
    },
    {
      path: 'mail',
      name: 'mail',
      parentPath: '/system',
      icon: '',
      menu: true,
    },
    {
      path: 'customization',
      name: 'customization',
      parentPath: '/system',
      icon: '',
      menu: true,
    },
    {
      path: 'authorization',
      name: 'authorization',
      parentPath: '/system',
      icon: '',
      menu: true,
    },
  ],
}
