export default {
  path: '/task',
  name: 'task',
  view: 'task',
  parentPath: '/',
  redirect: '/task/personal',
  icon: '',
  menu: true,
  order: 20,
  children: [
    {
      path: 'personal',
      name: 'personal',
      parentPath: '/task',
      icon: '',
      menu: true,
    },
    {
      path: 'scan',
      name: 'scan',
      parentPath: '/task',
      icon: '',
      menu: true,
    },
    {
      path: 'history',
      name: 'history',
      parentPath: '/task',
      icon: '',
      menu: true,
    },
    {
      path: 'profile',
      name: 'profile',
      parentPath: '/task',
      icon: '',
      menu: true,
    },
  ],
}
